# BIGIN_KITTY_THEME
# Catppuccin-Mocha
include ./theme.conf
# END_KITTY_THEME
#

shell /usr/bin/fish
# font_family MesloLGS Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono NL"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13
# END_KITTY_FONTS

# Window layout
window_margin_width 6
enabled_layouts Tall, *

# background_opacity 0.9

hide_window_decorations yes # could not find different in hyprland

# Animations
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0

